Program = [{
  "Description": "    Final",
  "Program": "Freestyle",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "12",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Combi",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211497"
}, {
  "Description": "    Final",
  "Program": "Freestyle",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "5",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Duo",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211493"
}, {
  "Description": "    Final",
  "Program": "Freestyle",
  "On_next_round": "",
  "active": "false",
  "Gender": "Woman",
  "Participants": "10",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211489"
}, {
  "Description": "    Final",
  "Program": "Freestyle",
  "On_next_round": "",
  "active": "false",
  "Gender": "Woman",
  "Participants": "3",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000211485"
}, {
  "Description": "    Final",
  "Program": "Freestyle",
  "On_next_round": "",
  "active": "false",
  "Gender": "Man",
  "Participants": "7",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211481"
}, {
  "Description": "     Final",
  "Program": "Conventional",
  "On_next_round": "3",
  "active": "false",
  "Gender": "Woman",
  "Participants": "3",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211469"
}, {
  "Description": " General look",
  "Program": "Conventional",
  "On_next_round": "",
  "active": "false",
  "Gender": "Woman",
  "Participants": "3",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211465"
}, {
  "Description": "     Final",
  "Program": "Conventional",
  "On_next_round": "3",
  "active": "false",
  "Gender": "Man",
  "Participants": "3",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211453"
}, {
  "Description": " General look",
  "Program": "Conventional",
  "On_next_round": "",
  "active": "false",
  "Gender": "Man",
  "Participants": "3",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211449"
}, {
  "Description": "     Final",
  "Program": "Standard",
  "On_next_round": "12",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "12",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Combi",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211391"
}, {
  "Description": " General look",
  "Program": "Standard",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "12",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Combi",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211385"
}, {
  "Description": "     Final",
  "Program": "Latin",
  "On_next_round": "14",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "14",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Combi",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211309"
}, {
  "Description": " General look",
  "Program": "Latin",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "14",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Combi",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211301"
}, {
  "Description": "     Final",
  "Program": "Standard",
  "On_next_round": "6",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "6",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211271"
}, {
  "Description": " General look",
  "Program": "Standard",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "6",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211267"
}, {
  "Description": "     Final",
  "Program": "Latin",
  "On_next_round": "7",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "7",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Duo",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211219"
}, {
  "Description": " General look",
  "Program": "Latin",
  "On_next_round": "",
  "active": "false",
  "Gender": "Mixed",
  "Participants": "7",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Duo",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211213"
}, {
  "Description": "     Final",
  "Program": "Conventional",
  "On_next_round": "12",
  "active": "false",
  "Gender": "Woman",
  "Participants": "20",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211115"
}, {
  "Description": "   Re-dance",
  "Program": "Conventional",
  "On_next_round": "5",
  "active": "false",
  "Gender": "Woman",
  "Participants": "13",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211107"
}, {
  "Description": "  1st Round",
  "Program": "Conventional",
  "On_next_round": "7",
  "active": "false",
  "Gender": "Woman",
  "Participants": "20",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000211097"
}, {
  "Description": "     Final",
  "Program": "Conventional",
  "On_next_round": "5",
  "active": "false",
  "Gender": "Woman",
  "Participants": "5",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000211067"
}, {
  "Description": " General look",
  "Program": "Conventional",
  "On_next_round": "",
  "active": "false",
  "Gender": "Woman",
  "Participants": "5",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000211063"
}, {
  "Description": "     Final",
  "Program": "Conventional",
  "On_next_round": "11",
  "active": "false",
  "Gender": "Man",
  "Participants": "11",
  "Marks": "true",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000211005"
}, {
  "Description": " General look",
  "Program": "Conventional",
  "On_next_round": "",
  "active": "false",
  "Gender": "Man",
  "Participants": "11",
  "Marks": "false",
  "Dance_order": "",
  "Championship": "Чемпионат России 2018 \"Танцы на колясках\"",
  "Dance": "",
  "Stage": "",
  "Event": "Single",
  "Class": "Class 1+2",
  "Level": "",
  "ID": "3639887000000210999"
}]
