 Program = [{
   "Description": "    Final",
   "Program": "Freestyle",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "12",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Combi",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000236072"
 }, {
   "Description": "    Final",
   "Program": "Freestyle",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "7",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Duo",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000236068"
 }, {
   "Description": "    Final",
   "Program": "Freestyle",
   "On_next_round": "",
   "active": false,
   "Gender": "Woman",
   "Participants": "13",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000236064"
 }, {
   "Description": "    Final",
   "Program": "Freestyle",
   "On_next_round": "",
   "active": false,
   "Gender": "Woman",
   "Participants": "3",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1",
   "Level": "",
   "ID": "3639887000000236060"
 }, {
   "Description": "    Final",
   "Program": "Freestyle",
   "On_next_round": "",
   "active": false,
   "Gender": "Man",
   "Participants": "7",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000236056"
 }, {
   "Description": "     Final",
   "Program": "Conventional",
   "On_next_round": "3",
   "active": false,
   "Gender": "Woman",
   "Participants": "3",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single junior",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000236044"
 }, {
   "Description": " General look",
   "Program": "Conventional",
   "On_next_round": "",
   "active": false,
   "Gender": "Woman",
   "Participants": "3",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single junior",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000236040"
 }, {
   "Description": "     Final",
   "Program": "Conventional",
   "On_next_round": "3",
   "active": false,
   "Gender": "Man",
   "Participants": "3",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single junior",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000236028"
 }, {
   "Description": " General look",
   "Program": "Conventional",
   "On_next_round": "",
   "active": false,
   "Gender": "Man",
   "Participants": "3",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single junior",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000236024"
 }, {
   "Description": "     Final",
   "Program": "Standard",
   "On_next_round": "12",
   "active": false,
   "Gender": "Mixed",
   "Participants": "12",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Combi",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230966"
 }, {
   "Description": " General look",
   "Program": "Standard",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "12",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Combi",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230960"
 }, {
   "Description": "     Final",
   "Program": "Latin",
   "On_next_round": "14",
   "active": false,
   "Gender": "Mixed",
   "Participants": "14",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Combi",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230884"
 }, {
   "Description": " General look",
   "Program": "Latin",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "14",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Combi",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230876"
 }, {
   "Description": "     Final",
   "Program": "Standard",
   "On_next_round": "5",
   "active": false,
   "Gender": "Mixed",
   "Participants": "5",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Duo",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000230846"
 }, {
   "Description": " General look",
   "Program": "Standard",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "5",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Duo",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000230842"
 }, {
   "Description": "     Final",
   "Program": "Latin",
   "On_next_round": "7",
   "active": false,
   "Gender": "Mixed",
   "Participants": "7",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Duo",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230794"
 }, {
   "Description": " General look",
   "Program": "Latin",
   "On_next_round": "",
   "active": false,
   "Gender": "Mixed",
   "Participants": "7",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Duo",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230788"
 }, {
   "Description": "     Final",
   "Program": "Conventional",
   "On_next_round": "12",
   "active": false,
   "Gender": "Woman",
   "Participants": "19",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000230698"
 }, {
   "Description": "   Re-dance",
   "Program": "Conventional",
   "On_next_round": "5",
   "active": false,
   "Gender": "Woman",
   "Participants": "12",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000230692"
 }, {
   "Description": "  1st Round",
   "Program": "Conventional",
   "On_next_round": "7",
   "active": false,
   "Gender": "Woman",
   "Participants": "19",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 2",
   "Level": "",
   "ID": "3639887000000230682"
 }, {
   "Description": "     Final",
   "Program": "Conventional",
   "On_next_round": "5",
   "active": false,
   "Gender": "Woman",
   "Participants": "5",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1",
   "Level": "",
   "ID": "3639887000000230652"
 }, {
   "Description": " General look",
   "Program": "Conventional",
   "On_next_round": "",
   "active": false,
   "Gender": "Woman",
   "Participants": "5",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1",
   "Level": "",
   "ID": "3639887000000230648"
 }, {
   "Description": "     Final",
   "Program": "Conventional",
   "On_next_round": "11",
   "active": false,
   "Gender": "Man",
   "Participants": "11",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230590"
 }, {
   "Description": " General look",
   "Program": "Conventional",
   "On_next_round": "",
   "active": false,
   "Gender": "Man",
   "Participants": "11",
   "Marks": false,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "Single",
   "Class": "Class 1+2",
   "Level": "",
   "ID": "3639887000000230584"
 }, {
   "Description": "Technical skills",
   "Program": "",
   "On_next_round": "",
   "active": false,
   "Gender": "",
   "Participants": "",
   "Marks": true,
   "Dance_order": "",
   "Championship": "Чемпионат России 2018 'Танцы на колясках'",
   "Dance": "",
   "Stage": "",
   "Event": "",
   "Class": "",
   "Level": "",
   "ID": "3639887000000230528"
 }]