Entries = [{
  "Program": "Freestyle",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Зорин",
  "Number": "107",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230140",
  "Athlete_2Local_name": "Мария Толкачёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Константин Халтурин",
  "Number": "114",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230166",
  "Athlete_2Local_name": "Дивин Флорсиль Ниамби Нцегани",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "97",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230094",
  "Athlete_2Local_name": "Екатерина Смыкова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Назаров",
  "Number": "103",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230116",
  "Athlete_2Local_name": "Наталья Боровая",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Антонов",
  "Number": "104",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230120",
  "Athlete_2Local_name": "Анна Богатырёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Череповец",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Александр Ефимовский",
  "Number": "116",
  "Requestlub_organization_name": "ТК «Ступени»",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230490",
  "Athlete_2Local_name": "Наталья Викулова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Соликамск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Вячеслав Вивсянник",
  "Number": "106",
  "Requestlub_organization_name": "ТСК '13 квартал'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230136",
  "Athlete_2Local_name": "Татьяна Котляр",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Максим Седаков",
  "Number": "108",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230144",
  "Athlete_2Local_name": "Светлана Кукушкина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Ломин",
  "Number": "95",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230078",
  "Athlete_2Local_name": "Ольга Телякова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Тверь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Роман Щербатых",
  "Number": "111",
  "Requestlub_organization_name": "",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230158",
  "Athlete_2Local_name": "Нина Гожева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Н. Уренгой",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Даниил Кравченко",
  "Number": "112",
  "Requestlub_organization_name": "ТСК 'Шарм+па' МБУ ДО 'ДТТЮ 'Дружба'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230160",
  "Athlete_2Local_name": "Екатерина Янечкина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Раушан Тагиров",
  "Number": "113",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230162",
  "Athlete_2Local_name": "Анна Мартюшева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Зорин",
  "Number": "107",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230138",
  "Athlete_2Local_name": "Мария Толкачёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Александр Булгаров",
  "Number": "101",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230104",
  "Athlete_2Local_name": "Екатерина Ярошенко",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Назаров",
  "Number": "103",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230114",
  "Athlete_2Local_name": "Наталья Боровая",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Антонов",
  "Number": "104",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230118",
  "Athlete_2Local_name": "Анна Богатырёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Блинов",
  "Number": "105",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230128",
  "Athlete_2Local_name": "Регина Кочергина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Соликамск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Вячеслав Вивсянник",
  "Number": "106",
  "Requestlub_organization_name": "ТСК '13 квартал'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230134",
  "Athlete_2Local_name": "Татьяна Котляр",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Максим Седаков",
  "Number": "108",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230142",
  "Athlete_2Local_name": "Светлана Кукушкина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Омск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Алексей Голиков",
  "Number": "94",
  "Requestlub_organization_name": "ОООО 'Танцы без границ'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230072",
  "Athlete_2Local_name": "Наталья Ровенская",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Алексей Серищев",
  "Number": "109",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230150",
  "Athlete_2Local_name": "Ирина Королёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Ломин",
  "Number": "95",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230076",
  "Athlete_2Local_name": "Ольга Телякова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Захар Шибакин",
  "Number": "110",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230154",
  "Athlete_2Local_name": "Елена Готовцева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Тверь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Роман Щербатых",
  "Number": "111",
  "Requestlub_organization_name": "",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230156",
  "Athlete_2Local_name": "Нина Гожева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Омск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Дмитрий Рылов",
  "Number": "96",
  "Requestlub_organization_name": "ОООО 'Танцы без границ'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230082",
  "Athlete_2Local_name": "Юлия Курочкина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "97",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230092",
  "Athlete_2Local_name": "Екатерина Смыкова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Владимир Золотарёв",
  "Number": "93",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230068",
  "Athlete_2Local_name": "Марина Котманова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Юрий Вишневский",
  "Number": "102",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230108",
  "Athlete_2Local_name": "Элеонора Гайнуллина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Москва",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Александр Ляпин",
  "Number": "98",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230096",
  "Athlete_2Local_name": "Ирина Гордеева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Александр Скобелев",
  "Number": "99",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230098",
  "Athlete_2Local_name": "Наталья Жила",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Станислав Шешуков",
  "Number": "100",
  "Requestlub_organization_name": "РОО 'ФИСТО'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230100",
  "Athlete_2Local_name": "Татьяна Скворцова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Александр Булгаров",
  "Number": "101",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230102",
  "Athlete_2Local_name": "Екатерина Ярошенко",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Назаров",
  "Number": "103",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230112",
  "Athlete_2Local_name": "Наталья Боровая",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Альберт Заббаров",
  "Number": "115",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230226",
  "Athlete_2Local_name": "Екатерина Мочалова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Омск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Алексей Голиков",
  "Number": "94",
  "Requestlub_organization_name": "ОООО 'Танцы без границ'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230070",
  "Athlete_2Local_name": "Наталья Ровенская",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Олег Ломин",
  "Number": "95",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230074",
  "Athlete_2Local_name": "Ольга Телякова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Омск",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Дмитрий Рылов",
  "Number": "96",
  "Requestlub_organization_name": "ОООО 'Танцы без границ'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230080",
  "Athlete_2Local_name": "Юлия Курочкина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "97",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Combi",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230090",
  "Athlete_2Local_name": "Екатерина Смыкова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Юрий Вишневский",
  "Number": "81",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230110",
  "Athlete_2Local_name": "Елена Замыслова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Севастополь/Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Игорь Давыдов",
  "Number": "88",
  "Requestlub_organization_name": "ГКУ 'ЦАС Инваспорт', КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230206",
  "Athlete_2Local_name": "Юлия Давыдова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "86",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230186",
  "Athlete_2Local_name": "Ксения Гиниятуллина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Максим Загорский",
  "Number": "91",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230236",
  "Athlete_2Local_name": "Ирина Карамышева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Вадим Самойлов",
  "Number": "92",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230478",
  "Athlete_2Local_name": "Кристина Нестерова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Антонов",
  "Number": "82",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230126",
  "Athlete_2Local_name": "Александра Бердник",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Максим Седаков",
  "Number": "83",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230148",
  "Athlete_2Local_name": "Галина Рыжкова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Севастополь/Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Игорь Давыдов",
  "Number": "88",
  "Requestlub_organization_name": "ГКУ 'ЦАС Инваспорт', КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230204",
  "Athlete_2Local_name": "Юлия Давыдова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "86",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230184",
  "Athlete_2Local_name": "Ксения Гиниятуллина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "87",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230198",
  "Athlete_2Local_name": "Мария Маралёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Москва",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Виталий Жиленко",
  "Number": "89",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230214",
  "Athlete_2Local_name": "Нурсина Галиева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Тамбов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Валерий Переславцев",
  "Number": "90",
  "Requestlub_organization_name": "ТОГБУК 'Цвета радуги'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230220",
  "Athlete_2Local_name": "Надежда Полещук",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Антонов",
  "Number": "82",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230124",
  "Athlete_2Local_name": "Александра Бердник",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Latin",
  "RequestSingle_Line2": "Серпухов",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Алексей Серищев",
  "Number": "84",
  "Requestlub_organization_name": "'Феникс' ГАПОУ МО 'ГК'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230152",
  "Athlete_2Local_name": "Елена Готовцева",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Москва",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Илья Гаськов",
  "Number": "85",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230174",
  "Athlete_2Local_name": "Елена Пастухова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "86",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230182",
  "Athlete_2Local_name": "Ксения Гиниятуллина",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "87",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230196",
  "Athlete_2Local_name": "Мария Маралёва",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Сергей Антонов",
  "Number": "82",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230122",
  "Athlete_2Local_name": "Александра Бердник",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Standard",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Mixed",
  "Athlete_1Local_name": "Максим Седаков",
  "Number": "83",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Duo",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230146",
  "Athlete_2Local_name": "Галина Рыжкова",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Man",
  "Athlete_1Local_name": "Юрий Вишневский",
  "Number": "11",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230106",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Севастополь/Пермь",
  "Gender": "Man",
  "Athlete_1Local_name": "Игорь Давыдов",
  "Number": "17",
  "Requestlub_organization_name": "ГКУ 'ЦАС Инваспорт', КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230200",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Максим Загорский",
  "Number": "21",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230228",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Андрей Рожинов",
  "Number": "45",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230414",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Сергей Поюнов",
  "Number": "48",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230438",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Вадим Самойлов",
  "Number": "52",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230470",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Man",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "10",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230084",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Соликамск",
  "Gender": "Man",
  "Athlete_1Local_name": "Вячеслав Вивсянник",
  "Number": "12",
  "Requestlub_organization_name": "ТСК '13 квартал'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230130",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "16",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230188",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Тамбов",
  "Gender": "Man",
  "Athlete_1Local_name": "Валерий Переславцев",
  "Number": "19",
  "Requestlub_organization_name": "ТОГБУК 'Цвета радуги'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230216",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Man",
  "Athlete_1Local_name": "Альберт Заббаров",
  "Number": "20",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230222",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Ванюкова",
  "Number": "23",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230246",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Давыдова",
  "Number": "24",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230256",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Замыслова",
  "Number": "25",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230266",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Марина Котманова",
  "Number": "26",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230276",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Наталья Ракитина",
  "Number": "27",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230284",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ольга Селиванова",
  "Number": "38",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230376",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алла Смелова",
  "Number": "39",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230378",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ольга Телякова",
  "Number": "40",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230388",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алёна Терентьева",
  "Number": "41",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230392",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Чирикова",
  "Number": "42",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230402",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Татьяна Бобровская",
  "Number": "28",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230286",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Снежана Фомина",
  "Number": "50",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230452",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Белявская",
  "Number": "51",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230460",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Волкова",
  "Number": "29",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230296",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Нестерова",
  "Number": "53",
  "Requestlub_organization_name": "СПб ООИ СК «Танец на колесах»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230480",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Нурсина Галиева",
  "Number": "30",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230306",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Woman",
  "Athlete_1Local_name": "Гульназ Акбашева",
  "Number": "54",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230488",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Наталья Жила",
  "Number": "31",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230316",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Карамышева",
  "Number": "32",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230324",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Мария Маралёва",
  "Number": "33",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230334",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Пастухова",
  "Number": "34",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230342",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Тамбов",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Полещук",
  "Number": "35",
  "Requestlub_organization_name": "ТОГБУК 'Цвета радуги'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230352",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Пономарёва",
  "Number": "36",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230356",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Дария Попова",
  "Number": "37",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230366",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Севастополь/Пермь",
  "Gender": "Man",
  "Athlete_1Local_name": "Игорь Давыдов",
  "Number": "17",
  "Requestlub_organization_name": "ГКУ 'ЦАС Инваспорт', КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230202",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Набережные Челны",
  "Gender": "Man",
  "Athlete_1Local_name": "Альберт Заббаров",
  "Number": "20",
  "Requestlub_organization_name": "Танцевально-Спортивный клуб 'STS'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230224",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Дмитрий Торгунаков",
  "Number": "22",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230244",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Man",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "10",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230086",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Соликамск",
  "Gender": "Man",
  "Athlete_1Local_name": "Вячеслав Вивсянник",
  "Number": "12",
  "Requestlub_organization_name": "ТСК '13 квартал'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230132",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Man",
  "Athlete_1Local_name": "Константин Халтурин",
  "Number": "13",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230164",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Тамбов",
  "Gender": "Man",
  "Athlete_1Local_name": "Валерий Переславцев",
  "Number": "19",
  "Requestlub_organization_name": "ТОГБУК 'Цвета радуги'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230218",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Ванюкова",
  "Number": "23",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230254",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Давыдова",
  "Number": "24",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230264",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Замыслова",
  "Number": "25",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 1",
  "Level": "",
  "ID": "3639887000000230274",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 1"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алла Смелова",
  "Number": "39",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230386",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Владивосток",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ольга Телякова",
  "Number": "40",
  "Requestlub_organization_name": "ДМООИ 'Ковчег'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230390",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алёна Терентьева",
  "Number": "41",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230400",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Омск",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Курочкина",
  "Number": "43",
  "Requestlub_organization_name": "ОООО 'Танцы без границ'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230410",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Н. Уренгой",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анна Лукьянчук",
  "Number": "44",
  "Requestlub_organization_name": "ТСК 'Шарм+па' МБУ ДО 'ДТТЮ 'Дружба'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230412",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Татьяна Бобровская",
  "Number": "28",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230294",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Белявская",
  "Number": "51",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230468",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Нурсина Галиева",
  "Number": "30",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230314",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Галина Рыжкова",
  "Number": "59",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230524",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Чебоксары",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анна Михайлова",
  "Number": "60",
  "Requestlub_organization_name": "",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230526",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Карамышева",
  "Number": "32",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230332",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Пастухова",
  "Number": "34",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230350",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Freestyle",
  "RequestSingle_Line2": "Тамбов",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Полещук",
  "Number": "35",
  "Requestlub_organization_name": "ТОГБУК 'Цвета радуги'",
  "Dance": "",
  "Event": "Single",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230354",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Сергей Поюнов",
  "Number": "48",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230442",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Сергей Поюнов",
  "Number": "48",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230440",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Вадим Самойлов",
  "Number": "52",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230472",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Максим Загорский",
  "Number": "21",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230230",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Дмитрий Торгунаков",
  "Number": "22",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230242",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Андрей Рожинов",
  "Number": "45",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230420",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Даниил Ширлин",
  "Number": "46",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230428",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Сергей Поюнов",
  "Number": "48",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230444",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Вадим Самойлов",
  "Number": "52",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230476",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Илья Гаськов",
  "Number": "14",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230172",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Михаил Гайдара",
  "Number": "57",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230512",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Man",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "15",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230180",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Ян Подольницкий",
  "Number": "58",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230520",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "16",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230194",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Виталий Жиленко",
  "Number": "18",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230212",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Максим Загорский",
  "Number": "21",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230234",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Дмитрий Торгунаков",
  "Number": "22",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230240",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Андрей Рожинов",
  "Number": "45",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230418",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Даниил Ширлин",
  "Number": "46",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230426",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Вадим Самойлов",
  "Number": "52",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230474",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Илья Гаськов",
  "Number": "14",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230170",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Михаил Гайдара",
  "Number": "57",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230510",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Man",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "15",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230178",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Ян Подольницкий",
  "Number": "58",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230518",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "16",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230192",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Виталий Жиленко",
  "Number": "18",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230210",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Максим Загорский",
  "Number": "21",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230232",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Дмитрий Торгунаков",
  "Number": "22",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230238",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Андрей Рожинов",
  "Number": "45",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230416",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Даниил Ширлин",
  "Number": "46",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230424",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Илья Гаськов",
  "Number": "14",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230168",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Михаил Гайдара",
  "Number": "57",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230508",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Man",
  "Athlete_1Local_name": "Павел Кравченко",
  "Number": "15",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230176",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Ян Подольницкий",
  "Number": "58",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230516",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Иван Селинский",
  "Number": "16",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230190",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Виталий Жиленко",
  "Number": "18",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230208",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Нурсина Галиева",
  "Number": "30",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230312",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Дария Попова",
  "Number": "37",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230370",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алла Смелова",
  "Number": "39",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230382",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Нурсина Галиева",
  "Number": "30",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230310",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Карамышева",
  "Number": "32",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230328",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Белявская",
  "Number": "51",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230464",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Пономарёва",
  "Number": "36",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230360",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Дария Попова",
  "Number": "37",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230368",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алла Смелова",
  "Number": "39",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230380",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Нурсина Галиева",
  "Number": "30",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230308",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Карамышева",
  "Number": "32",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230326",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Белявская",
  "Number": "51",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230462",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Нестерова",
  "Number": "53",
  "Requestlub_organization_name": "СПб ООИ СК «Танец на колесах»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230482",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Пономарёва",
  "Number": "36",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230358",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Замыслова",
  "Number": "25",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "High",
  "ID": "3639887000000230268",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Пономарёва",
  "Number": "36",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230362",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Замыслова",
  "Number": "25",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230272",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Эльвира Кчибекова",
  "Number": "55",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230496",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Дария Попова",
  "Number": "37",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230372",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Марина Котманова",
  "Number": "26",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230282",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Чебарева",
  "Number": "56",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230504",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алла Смелова",
  "Number": "39",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230384",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Татьяна Бобровская",
  "Number": "28",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230292",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алёна Терентьева",
  "Number": "41",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230398",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Волкова",
  "Number": "29",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230302",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Чирикова",
  "Number": "42",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230408",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ксения Гиниятуллина",
  "Number": "47",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230436",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Наталья Жила",
  "Number": "31",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230322",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Сударикова",
  "Number": "49",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230450",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Карамышева",
  "Number": "32",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230330",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Снежана Фомина",
  "Number": "50",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230458",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Мария Маралёва",
  "Number": "33",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230340",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Ванюкова",
  "Number": "23",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230252",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Белявская",
  "Number": "51",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230466",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Пастухова",
  "Number": "34",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230348",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Давыдова",
  "Number": "24",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230262",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Нестерова",
  "Number": "53",
  "Requestlub_organization_name": "СПб ООИ СК «Танец на колесах»",
  "Dance": "Rumba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230486",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Замыслова",
  "Number": "25",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230270",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Эльвира Кчибекова",
  "Number": "55",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230494",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Марина Котманова",
  "Number": "26",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230280",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Чебарева",
  "Number": "56",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230502",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Татьяна Бобровская",
  "Number": "28",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230290",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алёна Терентьева",
  "Number": "41",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230396",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Волкова",
  "Number": "29",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230300",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Чирикова",
  "Number": "42",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230406",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ксения Гиниятуллина",
  "Number": "47",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230434",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Наталья Жила",
  "Number": "31",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230320",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Сударикова",
  "Number": "49",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230448",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Снежана Фомина",
  "Number": "50",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230456",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Мария Маралёва",
  "Number": "33",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230338",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Ванюкова",
  "Number": "23",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230250",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Пастухова",
  "Number": "34",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230346",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Давыдова",
  "Number": "24",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230260",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Нестерова",
  "Number": "53",
  "Requestlub_organization_name": "СПб ООИ СК «Танец на колесах»",
  "Dance": "Samba",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230484",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Эльвира Кчибекова",
  "Number": "55",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230492",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Марина Котманова",
  "Number": "26",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230278",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Чебарева",
  "Number": "56",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230500",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Татьяна Бобровская",
  "Number": "28",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230288",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Алёна Терентьева",
  "Number": "41",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230394",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Волкова",
  "Number": "29",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230298",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Чирикова",
  "Number": "42",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230404",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ксения Гиниятуллина",
  "Number": "47",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230432",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Тюмень",
  "Gender": "Woman",
  "Athlete_1Local_name": "Наталья Жила",
  "Number": "31",
  "Requestlub_organization_name": "АНО ТСК 'Олимп'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230318",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Кристина Сударикова",
  "Number": "49",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230446",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Снежана Фомина",
  "Number": "50",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230454",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Мария Маралёва",
  "Number": "33",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230336",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Надежда Ванюкова",
  "Number": "23",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230248",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Елена Пастухова",
  "Number": "34",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230344",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Technics",
  "RequestSingle_Line2": "Пермь",
  "Gender": "Woman",
  "Athlete_1Local_name": "Юлия Давыдова",
  "Number": "24",
  "Requestlub_organization_name": "КГАОУДО 'Пермский РСТЦАС'",
  "Dance": "Waltz",
  "Event": "Single",
  "Class": "",
  "Level": "Normal",
  "ID": "3639887000000230258",
  "Athlete_2Local_name": "",
  "Class_to_participate": ""
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Андрей Рожинов",
  "Number": "45",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230422",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Москва",
  "Gender": "Man",
  "Athlete_1Local_name": "Даниил Ширлин",
  "Number": "46",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230430",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Воронеж",
  "Gender": "Man",
  "Athlete_1Local_name": "Григорий Фетисов",
  "Number": "10",
  "Requestlub_organization_name": "РООИ 'Соло Дэнс'",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230088",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Волкова",
  "Number": "29",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230304",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Анастасия Пономарёва",
  "Number": "36",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230364",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Дария Попова",
  "Number": "37",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single junior",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230374",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Михаил Гайдара",
  "Number": "57",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Single kids",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230514",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Man",
  "Athlete_1Local_name": "Ян Подольницкий",
  "Number": "58",
  "Requestlub_organization_name": "ГБУ «СПб ЦФКиС»",
  "Dance": "",
  "Event": "Single kids",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230522",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Санкт-Петербург",
  "Gender": "Woman",
  "Athlete_1Local_name": "Эльвира Кчибекова",
  "Number": "55",
  "Requestlub_organization_name": "ГБОУ ОЗЕРКИ",
  "Dance": "",
  "Event": "Single kids",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230498",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}, {
  "Program": "Conventional",
  "RequestSingle_Line2": "Москва",
  "Gender": "Woman",
  "Athlete_1Local_name": "Ирина Чебарева",
  "Number": "56",
  "Requestlub_organization_name": "РООИ 'Дуэт'",
  "Dance": "",
  "Event": "Single kids",
  "Class": "Class 2",
  "Level": "",
  "ID": "3639887000000230506",
  "Athlete_2Local_name": "",
  "Class_to_participate": "Class 2"
}]
