Entries = {
  "All_entries_local": [{
    "Program": "Freestyle",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Зорин",
    "Number": "127",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210010",
    "Athlete_2.Local_name": "Мария Толкачёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Назаров",
    "Number": "123",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209986",
    "Athlete_2.Local_name": "Наталья Боровая",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Антонов",
    "Number": "124",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209990",
    "Athlete_2.Local_name": "Анна Богатырёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Череповец",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Наталья Викулова",
    "Number": "136",
    "Request.lub_organization_name": "ТК «Ступени»",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210370",
    "Athlete_2.Local_name": "Александр Ефимовский",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Соликамск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Вячеслав Вивсянник",
    "Number": "126",
    "Request.lub_organization_name": "ТСК \"13 квартал\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210006",
    "Athlete_2.Local_name": "Татьяна Котляр",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Максим Седаков",
    "Number": "128",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210014",
    "Athlete_2.Local_name": "Светлана Кукушкина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Ломин",
    "Number": "115",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209948",
    "Athlete_2.Local_name": "Ольга Телякова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Тверь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Роман Щербатых",
    "Number": "131",
    "Request.lub_organization_name": "",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210028",
    "Athlete_2.Local_name": "Нина Гожева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Н. Уренгой",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Даниил Кравченко",
    "Number": "132",
    "Request.lub_organization_name": "",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210030",
    "Athlete_2.Local_name": "Екатерина Янечкина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Раушан Тагиров",
    "Number": "133",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210032",
    "Athlete_2.Local_name": "Анна Мартюшева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Константин Халтурин",
    "Number": "134",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210036",
    "Athlete_2.Local_name": "Дивин Флорсиль Ниамби Нцегани",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "117",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209964",
    "Athlete_2.Local_name": "Екатерина Смыкова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Зорин",
    "Number": "127",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210008",
    "Athlete_2.Local_name": "Мария Толкачёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Александр Булгаров",
    "Number": "121",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209974",
    "Athlete_2.Local_name": "Екатерина Ярошенко",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Назаров",
    "Number": "123",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209984",
    "Athlete_2.Local_name": "Наталья Боровая",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Антонов",
    "Number": "124",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209988",
    "Athlete_2.Local_name": "Анна Богатырёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Блинов",
    "Number": "125",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209998",
    "Athlete_2.Local_name": "Регина Кочергина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Соликамск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Вячеслав Вивсянник",
    "Number": "126",
    "Request.lub_organization_name": "ТСК \"13 квартал\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210004",
    "Athlete_2.Local_name": "Татьяна Котляр",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Максим Седаков",
    "Number": "128",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210012",
    "Athlete_2.Local_name": "Светлана Кукушкина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Омск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Алексей Голиков",
    "Number": "114",
    "Request.lub_organization_name": "ОООО \"Танцы без границ\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209942",
    "Athlete_2.Local_name": "Наталья Ровенская",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Алексей Серищев",
    "Number": "129",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210020",
    "Athlete_2.Local_name": "Ирина Королёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Ломин",
    "Number": "115",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209946",
    "Athlete_2.Local_name": "Ольга Телякова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Захар Шибакин",
    "Number": "130",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210024",
    "Athlete_2.Local_name": "Елена Готовцева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Тверь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Роман Щербатых",
    "Number": "131",
    "Request.lub_organization_name": "",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210026",
    "Athlete_2.Local_name": "Нина Гожева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Омск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Дмитрий Рылов",
    "Number": "116",
    "Request.lub_organization_name": "ОООО \"Танцы без границ\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209952",
    "Athlete_2.Local_name": "Юлия Курочкина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "117",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209962",
    "Athlete_2.Local_name": "Екатерина Смыкова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Владимир Золотарёв",
    "Number": "113",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000209938",
    "Athlete_2.Local_name": "Марина Котманова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Юрий Вишневский",
    "Number": "122",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000209978",
    "Athlete_2.Local_name": "Элеонора Гайнуллина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Александр Скобелев",
    "Number": "119",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209968",
    "Athlete_2.Local_name": "Наталья Жила",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Станислав Шешуков",
    "Number": "120",
    "Request.lub_organization_name": "РОО \"ФИСТО\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209970",
    "Athlete_2.Local_name": "Татьяна Скворцова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Александр Булгаров",
    "Number": "121",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209972",
    "Athlete_2.Local_name": "Екатерина Ярошенко",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Назаров",
    "Number": "123",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209982",
    "Athlete_2.Local_name": "Наталья Боровая",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Альберт Заббаров",
    "Number": "135",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210098",
    "Athlete_2.Local_name": "Екатерина Мочалова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Омск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Алексей Голиков",
    "Number": "114",
    "Request.lub_organization_name": "ОООО \"Танцы без границ\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209940",
    "Athlete_2.Local_name": "Наталья Ровенская",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Олег Ломин",
    "Number": "115",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209944",
    "Athlete_2.Local_name": "Ольга Телякова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Омск",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Дмитрий Рылов",
    "Number": "116",
    "Request.lub_organization_name": "ОООО \"Танцы без границ\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209950",
    "Athlete_2.Local_name": "Юлия Курочкина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "117",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209960",
    "Athlete_2.Local_name": "Екатерина Смыкова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Москва",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Александр Ляпин",
    "Number": "118",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Combi",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209966",
    "Athlete_2.Local_name": "Ирина Гордеева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Юрий Вишневский",
    "Number": "102",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000209980",
    "Athlete_2.Local_name": "Елена Замыслова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Севастополь/Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Игорь Давыдов",
    "Number": "110",
    "Request.lub_organization_name": "ГКУ \"ЦАС Инваспорт\", КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210078",
    "Athlete_2.Local_name": "Юлия Давыдова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "107",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210056",
    "Athlete_2.Local_name": "Ксения Гиниятуллина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Антонов",
    "Number": "103",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209996",
    "Athlete_2.Local_name": "Александра Бердник",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Максим Седаков",
    "Number": "104",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210018",
    "Athlete_2.Local_name": "Галина Рыжкова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Севастополь/Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Игорь Давыдов",
    "Number": "110",
    "Request.lub_organization_name": "ГКУ \"ЦАС Инваспорт\", КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210076",
    "Athlete_2.Local_name": "Юлия Давыдова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "107",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210054",
    "Athlete_2.Local_name": "Ксения Гиниятуллина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "109",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210070",
    "Athlete_2.Local_name": "Мария Маралёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Москва",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Виталий Жиленко",
    "Number": "111",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210086",
    "Athlete_2.Local_name": "Нурсина Галиева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Тамбов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Валерий Переславцев",
    "Number": "112",
    "Request.lub_organization_name": "ТОГБУК \"Цвета радуги\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210092",
    "Athlete_2.Local_name": "Надежда Полещук",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Антонов",
    "Number": "103",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209994",
    "Athlete_2.Local_name": "Александра Бердник",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Latin",
    "Request.Single_Line2": "Серпухов",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Алексей Серищев",
    "Number": "105",
    "Request.lub_organization_name": "\"Феникс\" ГАПОУ МО \"ГК\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210022",
    "Athlete_2.Local_name": "Елена Готовцева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Пермь",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "107",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210052",
    "Athlete_2.Local_name": "Ксения Гиниятуллина",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Липецк",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Александр Сафронов",
    "Number": "108",
    "Request.lub_organization_name": "ЛОООИ \"ФСТнК\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210058",
    "Athlete_2.Local_name": "Снежана Шепелева",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "109",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210068",
    "Athlete_2.Local_name": "Мария Маралёва",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Сергей Антонов",
    "Number": "103",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209992",
    "Athlete_2.Local_name": "Александра Бердник",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Максим Седаков",
    "Number": "104",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210016",
    "Athlete_2.Local_name": "Галина Рыжкова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Standard",
    "Request.Single_Line2": "Москва",
    "Gender": "Mixed",
    "Athlete_1.Local_name": "Илья Гаськов",
    "Number": "106",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Duo",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210044",
    "Athlete_2.Local_name": "Елена Пастухова",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Man",
    "Athlete_1.Local_name": "Юрий Вишневский",
    "Number": "61",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000209976",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Севастополь/Пермь",
    "Gender": "Man",
    "Athlete_1.Local_name": "Игорь Давыдов",
    "Number": "14",
    "Request.lub_organization_name": "ГКУ \"ЦАС Инваспорт\", КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210072",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Максим Загорский",
    "Number": "47",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210100",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Андрей Рожинов",
    "Number": "37",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210276",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Сергей Поюнов",
    "Number": "48",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210318",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вадим Самойлов",
    "Number": "49",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210352",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Man",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "60",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209954",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Соликамск",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вячеслав Вивсянник",
    "Number": "24",
    "Request.lub_organization_name": "ТСК \"13 квартал\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210000",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "29",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210060",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Тамбов",
    "Gender": "Man",
    "Athlete_1.Local_name": "Валерий Переславцев",
    "Number": "65",
    "Request.lub_organization_name": "ТОГБУК \"Цвета радуги\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210088",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Man",
    "Athlete_1.Local_name": "Альберт Заббаров",
    "Number": "66",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210094",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Ванюкова",
    "Number": "41",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210116",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Давыдова",
    "Number": "18",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210126",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Замыслова",
    "Number": "43",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210136",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Марина Котманова",
    "Number": "25",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210146",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Наталья Ракитина",
    "Number": "34",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210154",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Дария Попова",
    "Number": "33",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210240",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ольга Селиванова",
    "Number": "71",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210250",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алла Смелова",
    "Number": "36",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210252",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ольга Телякова",
    "Number": "39",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210256",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алёна Терентьева",
    "Number": "40",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210260",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Чирикова",
    "Number": "57",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210270",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Александра Бердник",
    "Number": "12",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210156",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Татьяна Бобровская",
    "Number": "68",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210158",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Белявская",
    "Number": "17",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210344",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Нестерова",
    "Number": "78",
    "Request.lub_organization_name": "СПб ООИ СК «Танец на колесах»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210360",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Волкова",
    "Number": "59",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210168",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Гульназ Акбашева",
    "Number": "79",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210368",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Нурсина Галиева",
    "Number": "20",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210178",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Наталья Жила",
    "Number": "44",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210188",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Севастополь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ксения Злобина",
    "Number": "69",
    "Request.lub_organization_name": "ГКУ«ЦАС Инваспорт»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210196",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Карамышева",
    "Number": "23",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210200",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Мария Маралёва",
    "Number": "28",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210208",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Пастухова",
    "Number": "70",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210216",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Тамбов",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Полещук",
    "Number": "53",
    "Request.lub_organization_name": "ТОГБУК \"Цвета радуги\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210226",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Пономарёва",
    "Number": "32",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210230",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Севастополь/Пермь",
    "Gender": "Man",
    "Athlete_1.Local_name": "Игорь Давыдов",
    "Number": "14",
    "Request.lub_organization_name": "ГКУ \"ЦАС Инваспорт\", КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210074",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Набережные Челны",
    "Gender": "Man",
    "Athlete_1.Local_name": "Альберт Заббаров",
    "Number": "66",
    "Request.lub_organization_name": "Танцевально-Спортивный клуб \"STS\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210096",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Дмитрий Торгунаков",
    "Number": "67",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210114",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Man",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "60",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209956",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Соликамск",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вячеслав Вивсянник",
    "Number": "24",
    "Request.lub_organization_name": "ТСК \"13 квартал\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210002",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Man",
    "Athlete_1.Local_name": "Константин Халтурин",
    "Number": "62",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210034",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Тамбов",
    "Gender": "Man",
    "Athlete_1.Local_name": "Валерий Переславцев",
    "Number": "65",
    "Request.lub_organization_name": "ТОГБУК \"Цвета радуги\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210090",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Ванюкова",
    "Number": "41",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210124",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Давыдова",
    "Number": "18",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210134",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Замыслова",
    "Number": "43",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 1",
    "ID": "3639887000000210144",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 1"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алла Смелова",
    "Number": "36",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210254",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Владивосток",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ольга Телякова",
    "Number": "39",
    "Request.lub_organization_name": "ДМООИ \"Ковчег\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210258",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алёна Терентьева",
    "Number": "40",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210268",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Омск",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Курочкина",
    "Number": "72",
    "Request.lub_organization_name": "ОООО \"Танцы без границ\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210272",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Н. Уренгой",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анна Лукьянчук",
    "Number": "73",
    "Request.lub_organization_name": "",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210274",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Татьяна Бобровская",
    "Number": "68",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210166",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Нурсина Галиева",
    "Number": "20",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210186",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Севастополь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ксения Злобина",
    "Number": "69",
    "Request.lub_organization_name": "ГКУ«ЦАС Инваспорт»",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210198",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Пастухова",
    "Number": "70",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210224",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Freestyle",
    "Request.Single_Line2": "Тамбов",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Полещук",
    "Number": "53",
    "Request.lub_organization_name": "ТОГБУК \"Цвета радуги\"",
    "Dance": "",
    "Event": "Single",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210228",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Сергей Поюнов",
    "Number": "48",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210322",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Сергей Поюнов",
    "Number": "48",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210320",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вадим Самойлов",
    "Number": "49",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210354",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Андрей Рожинов",
    "Number": "37",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210282",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Даниил Ширлин",
    "Number": "74",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210290",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210298",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210316",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Илья Гаськов",
    "Number": "63",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210042",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Сергей Поюнов",
    "Number": "48",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210324",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Man",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "46",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210050",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вадим Самойлов",
    "Number": "49",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210358",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "29",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210066",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210392",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Виталий Жиленко",
    "Number": "64",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210084",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210400",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Максим Загорский",
    "Number": "47",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210106",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Дмитрий Торгунаков",
    "Number": "67",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210112",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Андрей Рожинов",
    "Number": "37",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210280",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Даниил Ширлин",
    "Number": "74",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210288",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210296",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210314",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Илья Гаськов",
    "Number": "63",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210040",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Man",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "46",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210048",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Вадим Самойлов",
    "Number": "49",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210356",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "29",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210064",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210390",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Виталий Жиленко",
    "Number": "64",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210082",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210398",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Максим Загорский",
    "Number": "47",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210104",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Дмитрий Торгунаков",
    "Number": "67",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210110",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Андрей Рожинов",
    "Number": "37",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210278",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Даниил Ширлин",
    "Number": "74",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210286",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210294",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210312",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Илья Гаськов",
    "Number": "63",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210038",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Man",
    "Athlete_1.Local_name": "Павел Кравченко",
    "Number": "46",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210046",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Иван Селинский",
    "Number": "29",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210062",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210388",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Виталий Жиленко",
    "Number": "64",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210080",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210396",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Максим Загорский",
    "Number": "47",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210102",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Дмитрий Торгунаков",
    "Number": "67",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210108",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Нурсина Галиева",
    "Number": "20",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210184",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Пономарёва",
    "Number": "32",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210234",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Дария Попова",
    "Number": "33",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210244",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Нурсина Галиева",
    "Number": "20",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210182",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Карамышева",
    "Number": "23",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210204",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Пономарёва",
    "Number": "32",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210232",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Замыслова",
    "Number": "43",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210138",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Дария Попова",
    "Number": "33",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210242",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Нурсина Галиева",
    "Number": "20",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210180",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Карамышева",
    "Number": "23",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "High",
    "Class": "",
    "ID": "3639887000000210202",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Пастухова",
    "Number": "70",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210222",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Давыдова",
    "Number": "18",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210132",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Нестерова",
    "Number": "78",
    "Request.lub_organization_name": "СПб ООИ СК «Танец на колесах»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210366",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Пономарёва",
    "Number": "32",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210236",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Замыслова",
    "Number": "43",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210142",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210376",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Дария Попова",
    "Number": "33",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210246",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Марина Котманова",
    "Number": "25",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210152",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210384",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алёна Терентьева",
    "Number": "40",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210266",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Татьяна Бобровская",
    "Number": "68",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210164",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ксения Гиниятуллина",
    "Number": "45",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210304",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Волкова",
    "Number": "59",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210174",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210310",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Сударикова",
    "Number": "38",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210330",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Наталья Жила",
    "Number": "44",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210194",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210336",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Карамышева",
    "Number": "23",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210206",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Снежана Фомина",
    "Number": "55",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210342",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Мария Маралёва",
    "Number": "28",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210214",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Ванюкова",
    "Number": "41",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210122",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Белявская",
    "Number": "17",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Rumba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210350",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Давыдова",
    "Number": "18",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210130",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Нестерова",
    "Number": "78",
    "Request.lub_organization_name": "СПб ООИ СК «Танец на колесах»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210364",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Замыслова",
    "Number": "43",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210140",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210374",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Марина Котманова",
    "Number": "25",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210150",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210382",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алёна Терентьева",
    "Number": "40",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210264",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Татьяна Бобровская",
    "Number": "68",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210162",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ксения Гиниятуллина",
    "Number": "45",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210302",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Волкова",
    "Number": "59",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210172",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210308",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Сударикова",
    "Number": "38",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210328",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Наталья Жила",
    "Number": "44",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210192",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210334",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Снежана Фомина",
    "Number": "55",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210340",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Мария Маралёва",
    "Number": "28",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210212",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Ванюкова",
    "Number": "41",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210120",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Белявская",
    "Number": "17",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210348",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Пастухова",
    "Number": "70",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Samba",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210220",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Нестерова",
    "Number": "78",
    "Request.lub_organization_name": "СПб ООИ СК «Танец на колесах»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210362",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210372",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Марина Котманова",
    "Number": "25",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210148",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210380",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Алёна Терентьева",
    "Number": "40",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210262",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Татьяна Бобровская",
    "Number": "68",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210160",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ксения Гиниятуллина",
    "Number": "45",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210300",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Волкова",
    "Number": "59",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210170",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210306",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Кристина Сударикова",
    "Number": "38",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210326",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Тюмень",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Наталья Жила",
    "Number": "44",
    "Request.lub_organization_name": "АНО ТСК \"Олимп\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210190",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210332",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Снежана Фомина",
    "Number": "55",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210338",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Мария Маралёва",
    "Number": "28",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210210",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Ванюкова",
    "Number": "41",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210118",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Надежда Белявская",
    "Number": "17",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210346",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Елена Пастухова",
    "Number": "70",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210218",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Technics",
    "Request.Single_Line2": "Пермь",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Юлия Давыдова",
    "Number": "18",
    "Request.lub_organization_name": "КГАОУДО \"Пермский РСТЦАС\"",
    "Dance": "Waltz",
    "Event": "Single",
    "Level": "Normal",
    "Class": "",
    "ID": "3639887000000210128",
    "Athlete_2.Local_name": "",
    "Class_to_participate": ""
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Андрей Рожинов",
    "Number": "37",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210284",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Москва",
    "Gender": "Man",
    "Athlete_1.Local_name": "Даниил Ширлин",
    "Number": "74",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210292",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Воронеж",
    "Gender": "Man",
    "Athlete_1.Local_name": "Григорий Фетисов",
    "Number": "60",
    "Request.lub_organization_name": "РООИ \"Соло Дэнс\"",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000209958",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Дария Попова",
    "Number": "33",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210248",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Волкова",
    "Number": "59",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210176",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Анастасия Пономарёва",
    "Number": "32",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single junior",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210238",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Михаил Гайдара",
    "Number": "75",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Single kids",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210394",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Man",
    "Athlete_1.Local_name": "Ян Подольницкий",
    "Number": "50",
    "Request.lub_organization_name": "ГБУ «СПб ЦФКиС»",
    "Dance": "",
    "Event": "Single kids",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210402",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Санкт-Петербург",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Эльвира Кчибекова",
    "Number": "76",
    "Request.lub_organization_name": "ГБОУ ОЗЕРКИ",
    "Dance": "",
    "Event": "Single kids",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210378",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }, {
    "Program": "Conventional",
    "Request.Single_Line2": "Москва",
    "Gender": "Woman",
    "Athlete_1.Local_name": "Ирина Чебарева",
    "Number": "77",
    "Request.lub_organization_name": "РООИ \"Дуэт\"",
    "Dance": "",
    "Event": "Single kids",
    "Level": "",
    "Class": "Class 2",
    "ID": "3639887000000210386",
    "Athlete_2.Local_name": "",
    "Class_to_participate": "Class 2"
  }]
}