Athlethes1 = {
  All_Entries: [{
    Athlete_1: "Sedakov Maksim",
    Program: "Conventional",
    Athlete_2: "",
    Number: "10",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177006",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "10",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177014",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ryzhkova Galina",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "11",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177032",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ryzhkova Galina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "11",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177024",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Berdnik Aleksandra",
    Program: "Conventional",
    Athlete_2: "",
    Number: "12",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177038",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Conventional",
    Athlete_2: "",
    Number: "13",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177044",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "13",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177052",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Conventional",
    Athlete_2: "",
    Number: "14",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177064",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "14",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177072",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Prilebskih Igor",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "15",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177088",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Prilebskih Igor",
    Program: "Conventional",
    Athlete_2: "",
    Number: "15",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177086",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Shebaeva Kristina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "16",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177092",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Shebaeva Kristina",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "16",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177094",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Beliavskaiia Nadezhda",
    Program: "Conventional",
    Athlete_2: "",
    Number: "17",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177102",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydova Iuliia",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "18",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177120",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydova Iuliia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "18",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177112",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Dutkova Maria",
    Program: "Conventional",
    Athlete_2: "",
    Number: "19",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177126",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "SVK"
  }, {
    Athlete_1: "Dutkova Maria",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "19",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177128",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "SVK"
  }, {
    Athlete_1: "Galieva Nursina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "20",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177150",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Galieva Nursina",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "20",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177158",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Arapov Aleksey",
    Program: "Conventional",
    Athlete_2: "",
    Number: "21",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177164",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Arapov Aleksey",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "21",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177166",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kang Seoyeong",
    Program: "Conventional",
    Athlete_2: "",
    Number: "22",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177190",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "KOR"
  }, {
    Athlete_1: "Kang Seoyeong",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "22",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177192",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KOR"
  }, {
    Athlete_1: "Karamysheva Irina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "23",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177196",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vivsyannik Vyachaslav",
    Program: "Conventional",
    Athlete_2: "",
    Number: "24",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177210",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vivsyannik Vyachaslav",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "24",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177212",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kotmanova Marina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "25",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177220",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zhuravlev Alexey",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "26",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177228",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Zhuravlev Alexey",
    Program: "Conventional",
    Athlete_2: "",
    Number: "26",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177230",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Conventional",
    Athlete_2: "",
    Number: "27",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177246",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Maraleva Mariia",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "28",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177278",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Selinskii Ivan",
    Program: "Conventional",
    Athlete_2: "",
    Number: "29",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177286",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "30",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177306",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Conventional",
    Athlete_2: "",
    Number: "30",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177308",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Lee Youngho",
    Program: "Conventional",
    Athlete_2: "",
    Number: "31",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177318",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "KOR"
  }, {
    Athlete_1: "Ponomareva Anastasia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "32",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177322",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ponomareva Anastasia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "32",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177330",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Popova Daria",
    Program: "Conventional",
    Athlete_2: "",
    Number: "33",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177332",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Popova Daria",
    Program: "Conventional",
    Athlete_2: "",
    Number: "33",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177340",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rakitina Natalia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "34",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177342",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sadkowska Julia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "35",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177344",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "POL"
  }, {
    Athlete_1: "Sadkowska Julia",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "35",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177346",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "POL"
  }, {
    Athlete_1: "Sadkowska Julia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "35",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177348",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "POL"
  }, {
    Athlete_1: "Smelova Alla",
    Program: "Conventional",
    Athlete_2: "",
    Number: "36",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177356",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Smelova Alla",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "36",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177364",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rozhinov Andrei",
    Program: "Conventional",
    Athlete_2: "",
    Number: "37",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177374",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Teliakova Olga",
    Program: "Conventional",
    Athlete_2: "",
    Number: "39",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177382",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Teliakova Olga",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "39",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177384",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Terenteva Aliona",
    Program: "Conventional",
    Athlete_2: "",
    Number: "40",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177398",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Terenteva Aliona",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "40",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177406",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vaniukova Nadezhda",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "41",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177416",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vaniukova Nadezhda",
    Program: "Conventional",
    Athlete_2: "",
    Number: "41",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177408",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Svetlana",
    Program: "Conventional",
    Athlete_2: "",
    Number: "42",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177418",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Svetlana",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "42",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177420",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zamyslova Elena",
    Program: "Conventional",
    Athlete_2: "",
    Number: "43",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177424",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zamyslova Elena",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "43",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177432",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zhila Natalia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "44",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177434",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Giniiatullina Kseniia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "45",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177444",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Conventional",
    Athlete_2: "",
    Number: "46",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177456",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zagorskii Maksim",
    Program: "Conventional",
    Athlete_2: "",
    Number: "47",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177468",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Poiunov Sergey",
    Program: "Conventional",
    Athlete_2: "",
    Number: "48",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177476",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Samoilov Vadim",
    Program: "Conventional",
    Athlete_2: "",
    Number: "49",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177484",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Podolnichkii Ian",
    Program: "Conventional",
    Athlete_2: "",
    Number: "50",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177500",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Chekhovskii Timur",
    Program: "Conventional",
    Athlete_2: "",
    Number: "51",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177522",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Chekhovskii Timur",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "51",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177524",
    Gender: "Man",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Chepournova Natalia",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "52",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177530",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Poleschuk Nadezhda",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "53",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177532",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kasicka Helena",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "54",
    Dance: "",
    Event: "Single",
    Class: "Class 1",
    ID: "3639887000000177534",
    Gender: "Woman",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "SVK"
  }, {
    Athlete_1: "Chirikova Nadezhda",
    Program: "Conventional",
    Athlete_2: "",
    Number: "57",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177552",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Pfaifle Natalia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "58",
    Dance: "",
    Event: "Single",
    Class: "Class 2",
    ID: "3639887000000177554",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Anastasiia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "59",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177562",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Chebareva Irina",
    Program: "Conventional",
    Athlete_2: "",
    Number: "60",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177110",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kchibekova Elvira",
    Program: "Conventional",
    Athlete_2: "",
    Number: "61",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177204",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Krylova Mariia",
    Program: "Conventional",
    Athlete_2: "",
    Number: "62",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177254",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Logunova Elizaveta",
    Program: "Conventional",
    Athlete_2: "",
    Number: "63",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177256",
    Gender: "Woman",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fetisov Grigoriy",
    Program: "Conventional",
    Athlete_2: "",
    Number: "64",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177264",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Shirlin Daniil",
    Program: "Conventional",
    Athlete_2: "",
    Number: "65",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177492",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Gaidara Mikhail",
    Program: "Conventional",
    Athlete_2: "",
    Number: "66",
    Dance: "",
    Event: "Single junior",
    Class: "Class 2",
    ID: "3639887000000177504",
    Gender: "Man",
    Program_Dances: "Waltz,Samba,Rumba,Tango,Jive",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Standard",
    Athlete_2: "Ryzhkova Galina",
    Number: "87",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177034",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Freestyle",
    Athlete_2: "Ryzhkova Galina",
    Number: "87",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177036",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Standard",
    Athlete_2: "Berdnik Aleksandra",
    Number: "88",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177054",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Latin",
    Athlete_2: "Berdnik Aleksandra",
    Number: "88",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177056",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Freestyle",
    Athlete_2: "Davydova Iuliia",
    Number: "89",
    Dance: "",
    Event: "Duo",
    Class: "Class 1",
    ID: "3639887000000177122",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Latin",
    Athlete_2: "Davydova Iuliia",
    Number: "89",
    Dance: "",
    Event: "Duo",
    Class: "Class 1",
    ID: "3639887000000177124",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zhilenko Vitaly",
    Program: "Latin",
    Athlete_2: "Galieva Nursina",
    Number: "90",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177160",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Andersson Karl",
    Program: "Latin",
    Athlete_2: "Ihantola Hanna",
    Number: "91",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177186",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "FIN"
  }, {
    Athlete_1: "Andersson Karl",
    Program: "Standard",
    Athlete_2: "Ihantola Hanna",
    Number: "91",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177188",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "FIN"
  }, {
    Athlete_1: "Fetisov Grigoriy",
    Program: "Freestyle",
    Athlete_2: "Logunova Elizaveta",
    Number: "92",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177268",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fetisov Grigoriy",
    Program: "Latin",
    Athlete_2: "Logunova Elizaveta",
    Number: "92",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177270",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Selinskii Ivan",
    Program: "Freestyle",
    Athlete_2: "Maraleva Mariia",
    Number: "93",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177288",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Selinskii Ivan",
    Program: "Latin",
    Athlete_2: "Maraleva Mariia",
    Number: "93",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177290",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Selinskii Ivan",
    Program: "Standard",
    Athlete_2: "Maraleva Mariia",
    Number: "93",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177292",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Safronov Aleksandr",
    Program: "Standard",
    Athlete_2: "Shepeleva Snezhana",
    Number: "94",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177354",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vivsyannik Vyachaslav",
    Program: "Freestyle",
    Athlete_2: "Volkova Svetlana",
    Number: "95",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177422",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Latin",
    Athlete_2: "Giniiatullina Kseniia",
    Number: "96",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177464",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Standard",
    Athlete_2: "Giniiatullina Kseniia",
    Number: "96",
    Dance: "",
    Event: "Duo",
    Class: "Class 2",
    ID: "3639887000000177466",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Freestyle",
    Athlete_2: "Kukushkina Svetlana",
    Number: "97",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177016",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Latin",
    Athlete_2: "Kukushkina Svetlana",
    Number: "97",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177018",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Freestyle",
    Athlete_2: "Anastasova Olga",
    Number: "98",
    Dance: "",
    Event: "Combi",
    Class: "Class 1",
    ID: "3639887000000177074",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Latin",
    Athlete_2: "Bogatyreva Anna",
    Number: "99",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177080",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Freestyle",
    Athlete_2: "Bogatyreva Anna",
    Number: "99",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177082",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Prilebskih Igor",
    Program: "Freestyle",
    Athlete_2: "Kolosova Ekaterina",
    Number: "100",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177090",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Solc Martin",
    Program: "Freestyle",
    Athlete_2: "Dutkova Maria",
    Number: "101",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177134",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "SVK"
  }, {
    Athlete_1: "Solc Martin",
    Program: "Standard",
    Athlete_2: "Dutkova Maria",
    Number: "101",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177136",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "SVK"
  }, {
    Athlete_1: "Batani Leonardo",
    Program: "Latin",
    Athlete_2: "Galeotti Linda",
    Number: "102",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177146",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "ITA"
  }, {
    Athlete_1: "Batani Leonardo",
    Program: "Standard",
    Athlete_2: "Galeotti Linda",
    Number: "102",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177148",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "ITA"
  }, {
    Athlete_1: "Batani Leonardo",
    Program: "Freestyle",
    Athlete_2: "Galeotti Linda",
    Number: "102",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177144",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "ITA"
  }, {
    Athlete_1: "Arapov Aleksey",
    Program: "Freestyle",
    Athlete_2: "Kurochkina Ellina",
    Number: "103",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177168",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Pyykkonen Timo",
    Program: "Freestyle",
    Athlete_2: "Harju Tuuli",
    Number: "104",
    Dance: "",
    Event: "Combi",
    Class: "Class 1",
    ID: "3639887000000177176",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "FIN"
  }, {
    Athlete_1: "Pyykkonen Timo",
    Program: "Latin",
    Athlete_2: "Harju Tuuli",
    Number: "104",
    Dance: "",
    Event: "Combi",
    Class: "Class 1",
    ID: "3639887000000177178",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "FIN"
  }, {
    Athlete_1: "Pyykkonen Timo",
    Program: "Standard",
    Athlete_2: "Harju Tuuli",
    Number: "104",
    Dance: "",
    Event: "Combi",
    Class: "Class 1",
    ID: "3639887000000177180",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "FIN"
  }, {
    Athlete_1: "Baek Seungyup",
    Program: "Standard",
    Athlete_2: "Kang Seoyeong",
    Number: "105",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177194",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "KOR"
  }, {
    Athlete_1: "Vivsyannik Vyachaslav",
    Program: "Freestyle",
    Athlete_2: "Kotliar Tatiana",
    Number: "106",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177214",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vivsyannik Vyachaslav",
    Program: "Latin",
    Athlete_2: "Kotliar Tatiana",
    Number: "106",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177216",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zolotarev Vladimir",
    Program: "Standard",
    Athlete_2: "Kotmanova Marina",
    Number: "107",
    Dance: "",
    Event: "Combi",
    Class: "Class 1",
    ID: "3639887000000177224",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zhuravlev Alexey",
    Program: "Freestyle",
    Athlete_2: "Krivokhizhina Alena",
    Number: "108",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177232",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Freestyle",
    Athlete_2: "Krivokhizhina Anastasiya",
    Number: "109",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177248",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Latin",
    Athlete_2: "Krivokhizhina Anastasiya",
    Number: "109",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177250",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Standard",
    Athlete_2: "Krivokhizhina Anastasiya",
    Number: "109",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177252",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Stepanov Anton",
    Program: "Freestyle",
    Athlete_2: "Logunova Elizaveta",
    Number: "110",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177258",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Freestyle",
    Athlete_2: "Mirnykh Darya",
    Number: "111",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177310",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Latin",
    Athlete_2: "Mirnykh Darya",
    Number: "111",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177312",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Standard",
    Athlete_2: "Mirnykh Darya",
    Number: "111",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177314",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Lee Youngho",
    Program: "Latin",
    Athlete_2: "Park Youngseon",
    Number: "112",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177320",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "KOR"
  }, {
    Athlete_1: "Bashlykov Aleksandr",
    Program: "Latin",
    Athlete_2: "Schwabauer Natalia",
    Number: "113",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177350",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fetisov Grigoriy",
    Program: "Freestyle",
    Athlete_2: "Smykova Ekaterina",
    Number: "114",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177366",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Lomin Oleg",
    Program: "Latin",
    Athlete_2: "Teliakova Olga",
    Number: "115",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177394",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Lomin Oleg",
    Program: "Standard",
    Athlete_2: "Teliakova Olga",
    Number: "115",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177396",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Lomin Oleg",
    Program: "Freestyle",
    Athlete_2: "Teliakova Olga",
    Number: "115",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177392",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Skobelev Aleksandr",
    Program: "Standard",
    Athlete_2: "Zhila Natalia",
    Number: "116",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177438",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sheshukov Stanislav",
    Program: "Standard",
    Athlete_2: "Skvortcova Tatiana",
    Number: "117",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177442",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Podolnichkii Ian",
    Program: "Freestyle",
    Athlete_2: "Zueva Gloria",
    Number: "118",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177502",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Voronin Dmitriy",
    Program: "Freestyle",
    Athlete_2: "Shebaeva Kristina",
    Number: "119",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177516",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Voronin Dmitriy",
    Program: "Latin",
    Athlete_2: "Shebaeva Kristina",
    Number: "119",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177518",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Voronin Dmitriy",
    Program: "Standard",
    Athlete_2: "Shebaeva Kristina",
    Number: "119",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177520",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Chekhovskii Timur",
    Program: "Freestyle",
    Athlete_2: "Kurochkina Eliza",
    Number: "120",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177528",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rilov Dmitriy",
    Program: "Standard",
    Athlete_2: "Kurochkina Yulia",
    Number: "121",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177544",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Golikov Aleksei",
    Program: "Latin",
    Athlete_2: "Rovenskaia Natalia",
    Number: "122",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177548",
    Gender: "Mixed",
    Program_Dances: "Samba,Rumba,Jive,Cha-cha,Pasodoble",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vysochkin Dmitrii",
    Program: "Standard",
    Athlete_2: "Shaliutina Elena",
    Number: "123",
    Dance: "",
    Event: "Combi",
    Class: "Class 2",
    ID: "3639887000000177564",
    Gender: "Mixed",
    Program_Dances: "Waltz,Tango,V_Waltz,Quickstep,Foxtrot",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "170",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177506",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "171",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177508",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "172",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177510",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "173",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177512",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "174",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177514",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "175",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177542",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "",
    Program: "Freestyle",
    Athlete_2: "",
    Number: "176",
    Dance: "",
    Event: "Group",
    Class: "",
    ID: "3639887000000177546",
    Gender: "Mixed",
    Program_Dances: "Freestyle",
    Athlete_1_NPC: ""
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "10",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177012",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ryzhkova Galina",
    Program: "Technics",
    Athlete_2: "",
    Number: "11",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177030",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "13",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177050",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Technics",
    Athlete_2: "",
    Number: "14",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177070",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Beliavskaiia Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "17",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177108",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydova Iuliia",
    Program: "Technics",
    Athlete_2: "",
    Number: "18",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177118",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Galieva Nursina",
    Program: "Technics",
    Athlete_2: "",
    Number: "20",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177156",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Karamysheva Irina",
    Program: "Technics",
    Athlete_2: "",
    Number: "23",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177202",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Technics",
    Athlete_2: "",
    Number: "27",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177244",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Maraleva Mariia",
    Program: "Technics",
    Athlete_2: "",
    Number: "28",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177276",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Technics",
    Athlete_2: "",
    Number: "30",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177304",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Ponomareva Anastasia",
    Program: "Technics",
    Athlete_2: "",
    Number: "32",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177328",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Popova Daria",
    Program: "Technics",
    Athlete_2: "",
    Number: "33",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177338",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Smelova Alla",
    Program: "Technics",
    Athlete_2: "",
    Number: "36",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177362",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rozhinov Andrei",
    Program: "Technics",
    Athlete_2: "",
    Number: "37",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177372",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sudarikova Kristina",
    Program: "Technics",
    Athlete_2: "",
    Number: "38",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177380",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Terenteva Aliona",
    Program: "Technics",
    Athlete_2: "",
    Number: "40",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177404",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vaniukova Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "41",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177414",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zamyslova Elena",
    Program: "Technics",
    Athlete_2: "",
    Number: "43",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177430",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Giniiatullina Kseniia",
    Program: "Technics",
    Athlete_2: "",
    Number: "45",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177450",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Technics",
    Athlete_2: "",
    Number: "46",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177462",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zagorskii Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "47",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177474",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Poiunov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "48",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177482",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Samoilov Vadim",
    Program: "Technics",
    Athlete_2: "",
    Number: "49",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177490",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Podolnichkii Ian",
    Program: "Technics",
    Athlete_2: "",
    Number: "50",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177498",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fomina Snezhana",
    Program: "Technics",
    Athlete_2: "",
    Number: "55",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177540",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Anastasiia",
    Program: "Technics",
    Athlete_2: "",
    Number: "59",
    Dance: "Rumba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177560",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "10",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177010",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ryzhkova Galina",
    Program: "Technics",
    Athlete_2: "",
    Number: "11",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177028",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "13",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177048",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Technics",
    Athlete_2: "",
    Number: "14",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177068",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Beliavskaiia Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "17",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177106",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydova Iuliia",
    Program: "Technics",
    Athlete_2: "",
    Number: "18",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177116",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Galieva Nursina",
    Program: "Technics",
    Athlete_2: "",
    Number: "20",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177154",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Karamysheva Irina",
    Program: "Technics",
    Athlete_2: "",
    Number: "23",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177200",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Technics",
    Athlete_2: "",
    Number: "27",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177242",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Maraleva Mariia",
    Program: "Technics",
    Athlete_2: "",
    Number: "28",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177274",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Technics",
    Athlete_2: "",
    Number: "30",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177302",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Ponomareva Anastasia",
    Program: "Technics",
    Athlete_2: "",
    Number: "32",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177326",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Popova Daria",
    Program: "Technics",
    Athlete_2: "",
    Number: "33",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177336",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Smelova Alla",
    Program: "Technics",
    Athlete_2: "",
    Number: "36",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177360",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rozhinov Andrei",
    Program: "Technics",
    Athlete_2: "",
    Number: "37",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177370",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sudarikova Kristina",
    Program: "Technics",
    Athlete_2: "",
    Number: "38",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177378",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Terenteva Aliona",
    Program: "Technics",
    Athlete_2: "",
    Number: "40",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177402",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vaniukova Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "41",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177412",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zamyslova Elena",
    Program: "Technics",
    Athlete_2: "",
    Number: "43",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177428",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Giniiatullina Kseniia",
    Program: "Technics",
    Athlete_2: "",
    Number: "45",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177448",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Technics",
    Athlete_2: "",
    Number: "46",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177460",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zagorskii Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "47",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177472",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Poiunov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "48",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177480",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Samoilov Vadim",
    Program: "Technics",
    Athlete_2: "",
    Number: "49",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177488",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Podolnichkii Ian",
    Program: "Technics",
    Athlete_2: "",
    Number: "50",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177496",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fomina Snezhana",
    Program: "Technics",
    Athlete_2: "",
    Number: "55",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177538",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Anastasiia",
    Program: "Technics",
    Athlete_2: "",
    Number: "59",
    Dance: "Samba",
    Event: "Single",
    Class: "",
    ID: "3639887000000177558",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sedakov Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "10",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177008",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Ryzhkova Galina",
    Program: "Technics",
    Athlete_2: "",
    Number: "11",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177026",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Antonov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "13",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177046",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydov Igor",
    Program: "Technics",
    Athlete_2: "",
    Number: "14",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177066",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Beliavskaiia Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "17",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177104",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Davydova Iuliia",
    Program: "Technics",
    Athlete_2: "",
    Number: "18",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177114",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Galieva Nursina",
    Program: "Technics",
    Athlete_2: "",
    Number: "20",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177152",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Karamysheva Irina",
    Program: "Technics",
    Athlete_2: "",
    Number: "23",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177198",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Tolegenov Alibek",
    Program: "Technics",
    Athlete_2: "",
    Number: "27",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177240",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Maraleva Mariia",
    Program: "Technics",
    Athlete_2: "",
    Number: "28",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177272",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Manabayev Bagylan",
    Program: "Technics",
    Athlete_2: "",
    Number: "30",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177300",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "KAZ"
  }, {
    Athlete_1: "Ponomareva Anastasia",
    Program: "Technics",
    Athlete_2: "",
    Number: "32",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177324",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Popova Daria",
    Program: "Technics",
    Athlete_2: "",
    Number: "33",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177334",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Smelova Alla",
    Program: "Technics",
    Athlete_2: "",
    Number: "36",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177358",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Rozhinov Andrei",
    Program: "Technics",
    Athlete_2: "",
    Number: "37",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177368",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Sudarikova Kristina",
    Program: "Technics",
    Athlete_2: "",
    Number: "38",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177376",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Terenteva Aliona",
    Program: "Technics",
    Athlete_2: "",
    Number: "40",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177400",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Vaniukova Nadezhda",
    Program: "Technics",
    Athlete_2: "",
    Number: "41",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177410",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zamyslova Elena",
    Program: "Technics",
    Athlete_2: "",
    Number: "43",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177426",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Giniiatullina Kseniia",
    Program: "Technics",
    Athlete_2: "",
    Number: "45",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177446",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Kravchenko Pavel",
    Program: "Technics",
    Athlete_2: "",
    Number: "46",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177458",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Zagorskii Maksim",
    Program: "Technics",
    Athlete_2: "",
    Number: "47",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177470",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Poiunov Sergey",
    Program: "Technics",
    Athlete_2: "",
    Number: "48",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177478",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Samoilov Vadim",
    Program: "Technics",
    Athlete_2: "",
    Number: "49",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177486",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Podolnichkii Ian",
    Program: "Technics",
    Athlete_2: "",
    Number: "50",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177494",
    Gender: "Man",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Fomina Snezhana",
    Program: "Technics",
    Athlete_2: "",
    Number: "55",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177536",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Lukashenko Anastasiia",
    Program: "Technics",
    Athlete_2: "",
    Number: "56",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177550",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }, {
    Athlete_1: "Volkova Anastasiia",
    Program: "Technics",
    Athlete_2: "",
    Number: "59",
    Dance: "Waltz",
    Event: "Single",
    Class: "",
    ID: "3639887000000177556",
    Gender: "Woman",
    Program_Dances: "",
    Athlete_1_NPC: "RUS"
  }]
}
flag = false
if (flag) {
  _.each(Athlethes1.All_Entries, ({
    Athlete_1,
    Program,
    Athlete_2,
    Number,
    Dance,
    Event,
    Class,
    Gender,
    Athlete_1_NPC
  }) => {
    Athlethes.insert({
      Athlete_1,
      Program,
      Athlete_2,
      Number,
      Dance,
      Event,
      Class,
      Gender,
      Athlete_1_NPC
    })
  })
}